# Generated by Django 5.1.7 on 2025-03-30 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_disbursementvoucher_created_by_and_more'),
        ('persons', '0003_employee_daily_wage_rate_employee_monthly_salary_and_more'),
        ('purchases', '0002_alter_bill_created_by_alter_bill_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_index=True, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Received')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card Payment'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Payment Received',
                'verbose_name_plural': 'Payments Received',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_index=True, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Paid')),
                ('payee_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], max_length=10, verbose_name='Payee Type')),
                ('other_payee_name', models.CharField(blank=True, max_length=255, verbose_name='Other Payee Name')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card Payment'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('account_paid_from', models.ForeignKey(limit_choices_to={'account_subtype__in': ['BANK'], 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='accounts.chartofaccounts', verbose_name='Account Paid From')),
                ('bills', models.ManyToManyField(blank=True, related_name='payments_made', to='purchases.bill', verbose_name='Related Bills Paid')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('disbursement_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='accounts.disbursementvoucher', verbose_name='Related Disbursement Voucher')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='persons.employee', verbose_name='Employee Payee')),
            ],
            options={
                'verbose_name': 'Payment Made',
                'verbose_name_plural': 'Payments Made',
                'ordering': ['-payment_date'],
            },
        ),
    ]
