# Generated by Django 5.1.7 on 2025-03-30 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_disbursementvoucher_created_by_and_more'),
        ('core', '0002_address'),
        ('payments', '0001_initial'),
        ('persons', '0004_employeeadvance'),
        ('sales', '0002_alter_salesinvoice_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmade',
            name='employee_advance_issued',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made_for_advance', to='persons.employeeadvance', verbose_name='Related Employee Advance Issued'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='payments_made', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='persons.vendor', verbose_name='Vendor Payee'),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='account_deposited_to',
            field=models.ForeignKey(limit_choices_to={'account_subtype__in': ['BANK', 'OTHER_CURRENT_ASSET', 'CURRENT_ASSET'], 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='accounts.chartofaccounts', verbose_name='Account Deposited To'),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.customer', verbose_name='Customer Received From'),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='payments_received', to='sales.salesinvoice', verbose_name='Related Sales Invoices'),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='payments_received', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
