# Generated by Django 5.1.7 on 2025-04-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_chartofaccounts_account_subtype_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmade',
            name='employee_advance_issued',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made_for_advance', to='accounts.employeeadvance', verbose_name='Related Employee Advance Issued'),
        ),
    ]
