# Generated by Django 5.1.7 on 2025-03-29 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_address'),
        ('persons', '0002_customer_parent_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('project_code', models.CharField(blank=True, help_text='Unique code for internal tracking.', max_length=50, null=True, unique=True, verbose_name='Project Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Planned or actual completion date.', null=True, verbose_name='End Date')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated or allocated budget for the project.', max_digits=15, null=True, verbose_name='Budget Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='persons.customer', verbose_name='Customer')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
