# Generated by Django 5.1.7 on 2025-03-29 18:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_disbursementvoucher'),
        ('core', '0002_address'),
        ('inventory', '0001_initial'),
        ('persons', '0003_employee_daily_wage_rate_employee_monthly_salary_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(help_text='The invoice/reference number from the vendor.', max_length=100, verbose_name='Vendor Bill Number')),
                ('bill_date', models.DateField(db_index=True, verbose_name='Bill Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved for Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=10, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Amount Paid')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('disbursement_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='accounts.disbursementvoucher', verbose_name='Disbursement Voucher')),
                ('tags', models.ManyToManyField(blank=True, related_name='bills', to='core.tag', verbose_name='Tags')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Bill / Vendor Expense',
                'verbose_name_plural': 'Bills / Vendor Expenses',
                'ordering': ['-bill_date', '-bill_number'],
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Detailed description of item/service purchased.', verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=15, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated as Quantity * Unit Price.', max_digits=15, null=True, verbose_name='Line Total')),
                ('is_vatable', models.BooleanField(default=True, help_text='Check if this line item is subject to Value Added Tax.', verbose_name='Is VATable?')),
                ('bir_classification', models.CharField(blank=True, help_text='BIR Alphanumeric Tax Code (ATC) or classification, if applicable.', max_length=100, verbose_name='BIR Classification/ATC')),
                ('account', models.ForeignKey(limit_choices_to={'account_type__in': ['EXPENSE', 'ASSET'], 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='accounts.chartofaccounts', verbose_name='Expense/Asset Account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.bill', verbose_name='Bill')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='inventory.product', verbose_name='Product/Service')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_lines', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Bill Line',
                'verbose_name_plural': 'Bill Lines',
                'ordering': ['bill', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('vendor', 'bill_number'), name='unique_vendor_bill_number'),
        ),
    ]
