# Generated by Django 5.1.7 on 2025-04-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_billline_warehouse_alter_bill_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='approved_by_1',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approved_bills', to=settings.AUTH_USER_MODEL, verbose_name='Approver 1'),
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_by_final',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_bills', to=settings.AUTH_USER_MODEL, verbose_name='Final Approver'),
        ),
        migrations.AddField(
            model_name='bill',
            name='initiator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_bills', to=settings.AUTH_USER_MODEL, verbose_name='Initiator'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved (Ready to Pay/Received)'), ('REJECTED', 'Rejected'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
