# Generated by Django 5.1.7 on 2025-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_bill_approved_by_1_bill_approved_by_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval (L1)'), ('PENDING_APPROVAL_2', 'Pending Approval (L2)'), ('APPROVED', 'Approved (Ready to Pay/Received)'), ('REJECTED', 'Rejected'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
