# Generated by Django 5.1.7 on 2025-03-29 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(help_text='Unique number identifying the account (e.g., 10100).', max_length=20, unique=True, verbose_name='Account Number')),
                ('name', models.CharField(help_text="Descriptive name of the account (e.g., 'Cash - Operating Account').", max_length=255, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], help_text='The main classification (Asset, Liability, Equity, Revenue, Expense).', max_length=20, verbose_name='Major Account Type')),
                ('account_subtype', models.CharField(choices=[('CURRENT_ASSET', 'Current Asset'), ('BANK', 'Bank'), ('ACCOUNTS_RECEIVABLE', 'Accounts Receivable (A/R)'), ('INVENTORY', 'Inventory'), ('PREPAID_EXPENSES', 'Prepaid Expenses'), ('OTHER_CURRENT_ASSET', 'Other Current Asset'), ('FIXED_ASSET', 'Fixed Asset'), ('CURRENT_LIABILITY', 'Current Liability'), ('ACCOUNTS_PAYABLE', 'Accounts Payable (A/P)'), ('CREDIT_CARD', 'Credit Card'), ('ACCRUED_LIABILITIES', 'Accrued Liabilities'), ('UNEARNED_REVENUE', 'Unearned Revenue'), ('LONG_TERM_LIABILITY', 'Long-Term Liability'), ('OWNERS_EQUITY', "Owner's Equity"), ('RETAINED_EARNINGS', 'Retained Earnings'), ('SALES', 'Sales Revenue'), ('SERVICE_REVENUE', 'Service Revenue'), ('PROJECT_REVENUE', 'Project Revenue'), ('OTHER_INCOME', 'Other Income'), ('COGS', 'Cost of Goods Sold (COGS)'), ('OPERATING_EXPENSE', 'Operating Expense'), ('SALARIES_WAGES', 'Salaries and Wages'), ('RENT_EXPENSE', 'Rent Expense'), ('UTILITIES_EXPENSE', 'Utilities Expense'), ('DEPRECIATION', 'Depreciation Expense'), ('INTEREST_EXPENSE', 'Interest Expense'), ('OTHER_EXPENSE', 'Other Expense')], help_text='Specific classification within the major type (e.g., Bank, A/R, COGS).', max_length=50, verbose_name='Account Subtype')),
                ('description', models.TextField(blank=True, help_text='Optional detailed description or purpose of the account.', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot be used in new transactions.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(blank=True, help_text='Optional parent account for creating hierarchical charts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='accounts.chartofaccounts', verbose_name='Parent Account')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['account_number', 'name'],
            },
        ),
    ]
