# Generated by Django 5.1.7 on 2025-03-29 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementVoucher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dv_number', models.CharField(help_text='Unique number identifying this disbursement voucher.', max_length=50, unique=True, verbose_name='DV Number')),
                ('dv_date', models.DateField(db_index=True, verbose_name='DV Date')),
                ('payee_name', models.CharField(help_text='Name of the vendor, employee, or other payee.', max_length=255, verbose_name='Payee Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Disbursement Amount')),
                ('payment_method', models.CharField(blank=True, help_text='e.g., Check, Bank Transfer, Cash', max_length=50, verbose_name='Payment Method')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='Check Number')),
                ('status', models.CharField(choices=[('PREPARED', 'Prepared'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PREPARED', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes/Purpose')),
                ('bank_account', models.ForeignKey(blank=True, limit_choices_to={'account_subtype': 'BANK'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chartofaccounts', verbose_name='Bank/Cash Account Disbursed From')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Disbursement Voucher',
                'verbose_name_plural': 'Disbursement Vouchers',
                'ordering': ['-dv_date', '-dv_number'],
            },
        ),
    ]
