# Generated by Django 5.1.7 on 2025-04-02 13:23

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_disbursementvoucher_created_by_and_more'),
        ('persons', '0003_employee_daily_wage_rate_employee_monthly_salary_and_more'),
        ('projects', '0002_project_created_by_project_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_subtype',
            field=models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash / Petty Cash'), ('ACCOUNTS_RECEIVABLE', 'Accounts Receivable (A/R)'), ('EMPLOYEE_ADVANCES', 'Employee Advances (Asset)'), ('INVENTORY', 'Inventory'), ('PREPAID_EXPENSES', 'Prepaid Expenses'), ('OTHER_CURRENT_ASSET', 'Other Current Asset'), ('FIXED_ASSET', 'Fixed Asset'), ('ACCOUNTS_PAYABLE', 'Accounts Payable (A/P)'), ('CREDIT_CARD_PAYABLE', 'Credit Card Payable'), ('ACCRUED_LIABILITIES', 'Accrued Liabilities'), ('UNEARNED_REVENUE', 'Unearned Revenue'), ('CURRENT_LIABILITY', 'Other Current Liability'), ('LONG_TERM_LIABILITY', 'Long-Term Liability'), ('OWNERS_EQUITY', "Owner's Equity"), ('RETAINED_EARNINGS', 'Retained Earnings'), ('SALES', 'Sales Revenue'), ('SERVICE_REVENUE', 'Service Revenue'), ('PROJECT_REVENUE', 'Project Revenue'), ('OTHER_INCOME', 'Other Income'), ('COGS', 'Cost of Goods Sold (COGS)'), ('OPERATING_EXPENSE', 'Operating Expense'), ('SALARIES_WAGES', 'Salaries and Wages'), ('RENT_EXPENSE', 'Rent Expense'), ('UTILITIES_EXPENSE', 'Utilities Expense'), ('DEPRECIATION', 'Depreciation Expense'), ('INTEREST_EXPENSE', 'Interest Expense'), ('OTHER_EXPENSE', 'Other Expense')], help_text='Specific classification within the major type.', max_length=50, verbose_name='Account Subtype'),
        ),
        migrations.AlterField(
            model_name='disbursementvoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_subtype__in': ['BANK', 'CASH'], 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chartofaccounts', verbose_name='Bank/Cash Account Disbursed From'),
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_issued', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('amount_issued', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Issued')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('date_due', models.DateField(default=accounts.models.get_default_advance_due_date, verbose_name='Liquidation/Repayment Due Date')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTIALLY_LIQUIDATED', 'Partially Liquidated/Repaid'), ('LIQUIDATED', 'Fully Liquidated/Repaid'), ('CANCELLED', 'Cancelled')], db_index=True, default='ISSUED', max_length=25, verbose_name='Status')),
                ('amount_liquidated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of the advance accounted for by submitted expenses.', max_digits=15, verbose_name='Amount Liquidated (Expenses)')),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of the advance returned as cash by the employee.', max_digits=15, verbose_name='Amount Repaid (Cash)')),
                ('asset_account', models.ForeignKey(blank=True, help_text="The specific 'Employee Advances' asset account this pertains to.", limit_choices_to={'account_subtype': 'EMPLOYEE_ADVANCES'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.chartofaccounts', verbose_name='Asset Account')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='persons.employee', verbose_name='Employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_advances', to='projects.project', verbose_name='Related Project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Employee Advance',
                'verbose_name_plural': 'Employee Advances',
                'ordering': ['-date_issued', 'employee'],
            },
        ),
    ]
