# Generated by Django 5.1.7 on 2025-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_chartofaccounts_account_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='advance_number',
            field=models.CharField(blank=True, help_text='Unique number identifying this cash advance.', max_length=50, null=True, unique=True, verbose_name='Advance Number'),
        ),
        migrations.AlterField(
            model_name='disbursementvoucher',
            name='check_number',
            field=models.CharField(blank=True, help_text='Check number or digital wallet transaction reference', max_length=50, verbose_name='Check/Reference Number'),
        ),
    ]
