# Generated by Django 5.1.7 on 2025-04-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeeadvance_advance_number_and_more'),
        ('projects', '0003_alter_project_created_by_alter_project_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementvoucher',
            name='approved_by_1',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approved_dvs', to=settings.AUTH_USER_MODEL, verbose_name='Approver 1'),
        ),
        migrations.AddField(
            model_name='disbursementvoucher',
            name='approved_by_final',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_dvs', to=settings.AUTH_USER_MODEL, verbose_name='Final Approver'),
        ),
        migrations.AddField(
            model_name='disbursementvoucher',
            name='initiator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_dvs', to=settings.AUTH_USER_MODEL, verbose_name='Initiator'),
        ),
        migrations.AddField(
            model_name='disbursementvoucher',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Link to a project if this DV is specifically for it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_vouchers', to='projects.project', verbose_name='Related Project'),
        ),
        migrations.AlterField(
            model_name='disbursementvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='disbursementvoucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved (Ready to Pay)'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='disbursementvoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
