# Generated by Django 5.1.7 on 2025-03-29 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_customer_parent_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_wage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter daily wage rate if payment type is Daily.', max_digits=10, null=True, verbose_name='Daily Wage Rate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter gross monthly salary if payment type is Salary.', max_digits=15, null=True, verbose_name='Monthly Salary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('SALARY', 'Monthly Salary'), ('DAILY', 'Daily Wage'), ('HOURLY', 'Hourly Rate'), ('PROJECT', 'Project Based')], max_length=10, null=True, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to the Django user account for login, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='System User Account'),
        ),
    ]
