# Generated by Django 5.1.7 on 2025-04-05 13:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_employee_daily_wage_rate_employee_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approval_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Maximum amount this employee can approve without needing higher approval.', max_digits=15, null=True, verbose_name='Approval Limit Amount'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_ultimately_approve',
            field=models.BooleanField(default=False, help_text='Can this employee give final approval regardless of amount (within their workflow level)?', verbose_name='Can Ultimately Approve?'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='persons.employee', verbose_name='Direct Manager'),
        ),
    ]
