# Generated by Django 5.1.7 on 2025-03-30 09:09

import django.db.models.deletion
import django.utils.timezone
import persons.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_employee_daily_wage_rate_employee_monthly_salary_and_more'),
        ('projects', '0002_project_created_by_project_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_issued', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('amount_issued', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Issued')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('date_due', models.DateField(default=persons.models.get_default_advance_due_date, verbose_name='Liquidation/Repayment Due Date')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTIALLY_LIQUIDATED', 'Partially Liquidated/Repaid'), ('LIQUIDATED', 'Fully Liquidated/Repaid'), ('CANCELLED', 'Cancelled')], db_index=True, default='ISSUED', max_length=25, verbose_name='Status')),
                ('amount_liquidated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of the advance accounted for by submitted expenses.', max_digits=15, verbose_name='Amount Liquidated (Expenses)')),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of the advance returned as cash by the employee.', max_digits=15, verbose_name='Amount Repaid (Cash)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='persons.employee', verbose_name='Employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_advances', to='projects.project', verbose_name='Related Project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Employee Advance',
                'verbose_name_plural': 'Employee Advances',
                'ordering': ['-date_issued', 'employee'],
            },
        ),
    ]
