# Generated by Django 5.1.7 on 2025-03-30 08:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before taxes and discounts. Calculated from lines.', max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax amount. Calculated.', max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount due (subtotal + tax). Calculated.', max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated as Quantity * Unit Price.', max_digits=15, null=True, verbose_name='Line Total (Exclusive of Tax)'),
        ),
    ]
