# Generated by Django 5.1.7 on 2025-04-02 13:23

import django.utils.timezone
import sales.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesinvoiceline_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='is_vat_exempt',
            field=models.BooleanField(default=False, help_text='Check if this line item is exempt from VAT calculation.', verbose_name='VAT Exempt?'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Updated automatically by payments.', max_digits=15, verbose_name='Amount Received'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(default=sales.models.get_default_invoice_due_date, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of item/service sold (if not using product).', verbose_name='Description'),
        ),
    ]
