# Generated by Django 5.1.7 on 2025-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoiceline_is_vat_exempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of item/service sold (fills from product if blank).', verbose_name='Description'),
        ),
    ]
